AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain
#Redshift Parameters
  AdminUsername:
    Type: String
    Default: 'admin'
    Description: 'Admin username for the Redshift Serverless instance'
  AdminUserPassword:
    Type: String
    Default: 'Password28'
    NoEcho: true
    Description: 'Admin user password for the Redshift Serverless instance'
  redshiftPath:
    Type: String
    Description: 'S3 URL of the nested stack template'
  SubnetIds:
    Type: String
    Description: 'Subnet Ids'
    Default: subnet-0e02df7b9e58e3960,subnet-05d7a985f0bdf9b64,subnet-04fc4b2eacf4f1df4

Resources:
  RedshiftServerlessStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref redshiftPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        AdminUsername: !Ref AdminUsername
        AdminUserPassword: !Ref AdminUserPassword
        # VPCSecurityGroupIds: !Join [ ",", [!GetAtt RedshiftVPCStack.Outputs.SecurityGroupId]]
        SubnetIds: !Ref SubnetIds
        
            