AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  EnvType:
    Type: String
    Default: "sit"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain
#Redshift Parameters
  AdminUsername:
    Type: String
    Default: 'admin'
    Description: 'Admin username for the Redshift Serverless instance'
  AdminUserPassword:
    Type: String
    Default: 'Password28'
    NoEcho: true
    Description: 'Admin user password for the Redshift Serverless instance'
  redshiftPath:
    Type: String
    Description: 'S3 URL of the nested stack template'
  redshiftdbPath:
    Type: String
    Description: 'S3 URL of the nested stack template'    
  SubnetIds:
    Type: String
    Description: 'Subnet Ids'
    Default: subnet-0e02df7b9e58e3960,subnet-05d7a985f0bdf9b64,subnet-04fc4b2eacf4f1df4
  RedshiftEnvironment:
    Type: String
    Default: "nonprod"
    AllowedValues:
         - "nonprod"
         - "uat"
         - "prod"
    Description: 'Environment name of the Redshift instances'

Mappings:
  EnvironmentMapping:
    nonprod:
      Namespace: 'nonprod-ns'
      Workgroup: 'nonprod-workgroup'
    uat:
      Namespace: 'nonprod-uat-ns'
      Workgroup: 'nonprod-uat-workgroup'
    prod:
      Namespace: 'prod-ns'
      Workgroup: 'prod-workgroup'

Resources:
  RedshiftServerlessStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref redshiftPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        AdminUsername: !Ref AdminUsername
        AdminUserPassword: !Ref AdminUserPassword
        NamespaceName: !FindInMap [EnvironmentMapping, !Ref RedshiftEnvironment, Namespace]
        WorkgroupName: !FindInMap [EnvironmentMapping, !Ref RedshiftEnvironment, Workgroup]
        # VPCSecurityGroupIds: !Join [ ",", [!GetAtt RedshiftVPCStack.Outputs.SecurityGroupId]]
        SubnetIds: !Ref SubnetIds

  RedshiftDatabases:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref redshiftdbPath
      Parameters:
        WorkgroupName: !FindInMap [EnvironmentMapping, !Ref RedshiftEnvironment, Namespace]
        NamespaceName: !FindInMap [EnvironmentMapping, !Ref RedshiftEnvironment, Namespace]
        EnvType: !Ref EnvType
        
            