AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create Amazon Redshift Serverless resources.

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)

  DomainName:
    Type: String
    Description: The name of the domain  

  AdminUsername:
    Description: Master username for the Redshift Serverless database
    Type: String

  AdminUserPassword:
    Description: Master password for the Redshift Serverless database
    Type: String

  # VPCSecurityGroupIds:
  #   Description: Comma-separated list of security group IDs
  #   Type: CommaDelimitedList

  SubnetIds:
    Description: Comma-separated list of subnet IDs for the Redshift Serverless workgroup
    Type: CommaDelimitedList
  NSName:
    Type: String
    Description: The name of the domain
    Default: "nonprod-ns"

Conditions:
  NSvalidate: !Equals [ !Ref NSName, "yes" ]   

Resources:
  RedshiftNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Properties:
      NamespaceName: "nonprod-ns"
      DbName: "nonprod-dev"
      AdminUsername: !Ref AdminUsername
      AdminUserPassword: !Ref AdminUserPassword
      IamRoles: []  # Add IAM Role ARNs if needed
      LogExports:
        - userlog
        - connectionlog
        - useractivitylog
      Tags:
        - Key: EnvType
          Value: !Ref EnvType
        - Key: DomainName
          Value: !Ref DomainName

  RedshiftNamespace2:
    Type: AWS::RedshiftServerless::Namespace
    Condition: NSvalidate    
    Properties:
      NamespaceName: "nonprod-ns"
      DbName: "nonprod-dev2"
      AdminUsername: !Ref AdminUsername
      AdminUserPassword: !Ref AdminUserPassword
      IamRoles: []  # Add IAM Role ARNs if needed
      LogExports:
        - userlog
        - connectionlog
        - useractivitylog
      Tags:
        - Key: EnvType
          Value: !Ref EnvType
        - Key: DomainName
          Value: !Ref DomainName          
    

  RedshiftWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    Properties:
      WorkgroupName: "nonprod-workgroup"
      NamespaceName: !Ref RedshiftNamespace
      PubliclyAccessible: true
      SecurityGroupIds: 
        - !Ref RedshiftServerlessSecurityGroup
      SubnetIds: !Ref SubnetIds
      BaseCapacity: 8  # Measured in Redshift Processing Units (RPUs)

  RedshiftServerlessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: 'vpc-0e22305d886064b94'
      GroupDescription: Security group for Redshift Serverless
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 0.0.0.0/0  # Note: Adjust as needed for your security requirements      

Outputs:
  WorkgroupEndpoint:
    Description: The endpoint of the Redshift Serverless workgroup
    Value: !GetAtt RedshiftWorkgroup.Workgroup.Endpoint.Address