AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create Amazon Redshift Serverless resources.

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)

  DomainName:
    Type: String
    Description: The name of the domain  

  AdminUsername:
    Description: Master username for the Redshift Serverless database
    Type: String

  AdminUserPassword:
    Description: Master password for the Redshift Serverless database
    Type: String

  # VPCSecurityGroupIds:
  #   Description: Comma-separated list of security group IDs
  #   Type: CommaDelimitedList

  SubnetIds:
    Description: Comma-separated list of subnet IDs for the Redshift Serverless workgroup
    Type: CommaDelimitedList

  NamespaceName:
    Type: String
    Default: "nonprod-ns"
    Description: Name of the Redshift Serverless     

Conditions:
  CreateNamespace: !Or
    - !Equals [!Ref EnvType, "dev"]
    - !Equals [!Ref EnvType, "uat"]
    - !Equals [!Ref EnvType, "prod"]
  CreateWorkGroup: !Or
    - !Equals [!Ref EnvType, "dev"]
    - !Equals [!Ref EnvType, "uat"]
    - !Equals [!Ref EnvType, "prod"]    
    


Resources:
  RedshiftNamespace:
    Type: AWS::RedshiftServerless::Namespace
    Condition: CreateNamespace
    Properties:
      NamespaceName: "nonprod-ns"
      DbName: "nonprod-dev"
      AdminUsername: !Ref AdminUsername
      AdminUserPassword: !Ref AdminUserPassword
      IamRoles: []  # Add IAM Role ARNs if needed
      LogExports:
        - userlog
        - connectionlog
        - useractivitylog
      Tags:
        - Key: EnvType
          Value: !Ref EnvType
        - Key: DomainName
          Value: !Ref DomainName               
    
  RedshiftWorkgroup:
    Type: AWS::RedshiftServerless::Workgroup
    Condition: CreateWorkGroup    
    Properties:
      WorkgroupName: "nonprod-workgroup"
      NamespaceName: !Ref NamespaceName
      PubliclyAccessible: true
      SecurityGroupIds: 
        - !Ref RedshiftServerlessSecurityGroup
      SubnetIds: !Ref SubnetIds
      BaseCapacity: 8  # Measured in Redshift Processing Units (RPUs)

  RedshiftServerlessSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: 'vpc-0e22305d886064b94'
      GroupDescription: Security group for Redshift Serverless
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
          CidrIp: 0.0.0.0/0  # Note: Adjust as needed for your security requirements      

Outputs:
  WorkgroupEndpoint:
    Description: The endpoint of the Redshift Serverless workgroup
    Value: !GetAtt RedshiftWorkgroup.Workgroup.Endpoint.Address