version: 0.2
phases:
  build:
    commands:
      - |
        echo Build started on `date`
        filename="sample_config_file.txt"
        file=$CODEBUILD_SRC_DIR/config_files/"${filename}"
        echo $file
        echo Printing env variables
        echo "${env}"
        echo "${domain}"
        KEY="${domain}_${env}"
        echo "${KEY}"
        VALUE=$(grep "^${KEY}=" "$file" | sed -e "s/^${KEY}=//")
        if [ -z "$VALUE" ]; then
        echo "Key '$KEY' not found in $file"
        else echo "The value for '$KEY' is '$VALUE'"
        fi
        cfnfilename="main.yaml"
        cfnfile=$CODEBUILD_SRC_DIR/cfn/"${cfnfilename}"
        echo $cfnfile
        redshiftfilename="redshiftserverless.yaml"
        redshiftfile=$CODEBUILD_SRC_DIR/cfn/"${redshiftfilename}"
        echo $redshiftfile
        redshiftdbfilename="redshift-database.yaml"
        redshiftdbfile=$CODEBUILD_SRC_DIR/cfn/"${redshiftdbfilename}"
        echo $redshiftdbfile        
        aws s3 cp $redshiftfile s3://mycicd-bucket-ap2/cicd-files3/
        aws s3 cp $redshiftdbfile s3://mycicd-bucket-ap2/cicd-files3/           
        redshifturl=https://s3.amazonaws.com/mycicd-bucket-ap2/cicd-files3/redshiftserverless.yaml
        redshiftdburl=https://s3.amazonaws.com/mycicd-bucket-ap2/cicd-files3/redshift-database.yaml        
        aws cloudformation deploy \
          --template-file $cfnfile \
          --stack-name redshift-stack-sit \
          --parameter-overrides EnvType="{env}" DomainName="${domain}" RedshiftEnvironment="nonprod" redshiftPath="${redshifturl}" redshiftdbPath="{redshiftdburl}" \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
  post_build:
    commands:
      - aws cloudformation describe-stack-events --stack-name redshift-stack-sit
      - echo Build complete